# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "873709d982a38934eca71166e4533183"
application_url = "https://phoenix-ambient-compared-ict.trycloudflare.com"
embedded = true
name = "admin"
handle = "admin-77"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://phoenix-ambient-compared-ict.trycloudflare.com/auth/callback",
  "https://phoenix-ambient-compared-ict.trycloudflare.com/auth/shopify/callback",
  "https://phoenix-ambient-compared-ict.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
